apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.appName }}-service

  labels:
    app: {{ .Values.appName }}
    service: {{ .Values.appName }}-service
    {{- include "CoFloEnterprise.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}

  selector:
    app: {{ .Values.appName }}